CREATE TABLE NOTES(
    ID INT NOT NULL AUTO_INCREMENT,
    UUID VARCHAR(255) NOT NULL UNIQUE,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL,
    UPDATED DATE NOT NULL,
    PRIMARY KEY(ID)
);